name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        include:
          - name: Tests
            command: bin/tests
          - name: Lint
            command: bin/lint
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version-file: '.python-version'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements/*.txt
      - name: Install Python dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install -r requirements.txt --no-deps
      - name: Run ${{ matrix.name }}
        run: ${{ matrix.command }}
